#!/bin/bash

set +x
while getopts ":e:a:k:i:j:" opt; do
  case ${opt} in
    e )
      endpoint=$OPTARG
      ;;
    a )
      app_id=$OPTARG
      ;;
    k )
      api_key=$OPTARG
      ;;
    i )
      id=$OPTARG
      ;;
    \? )
      echo "Invalid option: -$OPTARG" 1>&2
      exit 1
      ;;
    : )
      echo "Option -$OPTARG requires an argument." 1>&2
      exit 1
      ;;
  esac
done

function check_jq() {
  if ! command -v jq &> /dev/null; then
    curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq-linux64
    chmod a+x jq-linux64 && mv jq-linux64 /usr/bin/jq
  fi
}

check_jq
clear () {
    echo ""
}

export -f clear
source ~/.bashrc

LOG_FILE="multi.log"
true > yabs.json
declare -A SCRIPT_NAMES_CMD=(
  ["yabs.sh"]="curl -sL yabs.sh | bash -s -- -w yabs.json -5"
  ["superspeed.sh"]="echo  -e "1"  | bash <(curl -Lso- https://git.io/superspeed_uxh)"
  ["openai-checker.sh"]="bash <(curl -Ls https://cdn.jsdelivr.net/gh/missuo/OpenAI-Checker/openai.sh)"
  ["media-unlock.sh"]="echo  -e "1"  |  bash <(curl -L -s check.unlock.media)"
  ["backtrace.sh"]="curl https://raw.githubusercontent.com/zhanghanyun/backtrace/main/install.sh -sSf | sh"
  ["besttrace.sh"]="wget -qO- git.io/besttrace | bash"
)

JSON='{ "raw": ['
for SCRIPT_NAME in "${!SCRIPT_NAMES_CMD[@]}"
do
  eval "${SCRIPT_NAMES_CMD["$SCRIPT_NAME"]}" 2>&1 |  tee >(sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,3})*)?[mGK]//g' > $LOG_FILE) 
  RESULT=$(<$LOG_FILE)
  ESCAPED_RESULT=$(printf '%s\n' "$RESULT" | jq -R -s @json)
  JSON+='{"name":"'$SCRIPT_NAME'", "result":'$ESCAPED_RESULT'},'
done
JSON=${JSON%?} # Remove the last comma
JSON+=']}'

unset -f clear
source ~/.bashrc

YABS=$(cat yabs.json)
MERGED_JSON=$(echo $JSON | jq --argjson arg1 "$YABS" '.YABS = $arg1 | {bench: .}')

set -x
curl --request POST \
  "https://$endpoint/app/$app_id/endpoint/data/v1/action/updateOne" \
  --header 'Content-Type: application/json' \
  --header "api-key: $api_key" \
  --data-raw "{
      \"dataSource\": \"Cluster0\",
      \"database\": \"vpslog\",
      \"collection\": \"servers\",
      \"filter\": { \"_id\": { \"\$oid\": \"$id\" } },
      \"update\": {
          \"\$set\": $MERGED_JSON
      }
  }"
